server {
    listen 80 default_server;
    server_name 159.195.219.237;
    return 301 https://podsalt-prime.com$request_uri;
}

upstream podsalt_unix_sock {
    server unix:///usr/share/nginx/socks/podsalt.sock;
}

server {
    listen 80;
    listen 443 ssl http2;
    server_name www.podsalt-prime.com;

    ssl_certificate     /root/.acme.sh/podsalt-prime.com_ecc/fullchain.cer;
    ssl_certificate_key /root/.acme.sh/podsalt-prime.com_ecc/podsalt-prime.com.key;

    return 301 https://podsalt-prime.com$request_uri;
}

server {
    listen 80;
    listen 443 ssl http2;

    ssl_certificate     /root/.acme.sh/podsalt-prime.com_ecc/fullchain.cer;
    ssl_certificate_key /root/.acme.sh/podsalt-prime.com_ecc/podsalt-prime.com.key;

    server_name podsalt-prime.com;
    charset utf-8;

    client_max_body_size 2G;

    # Security Headers
    # add_header Content-Security-Policy "default-src 'self' 'unsafe-inline' https://trustseal.enamad.ir https://simurgh.00-team.org https://www.googletagmanager.com https://www.google.com/";
    add_header Content-Security-Policy "default-src 'self' 'unsafe-inline' blob: data: *";
    add_header Permissions-Policy "geolocation=(self), microphone=()";
    add_header X-Content-Type-Options nosniff;
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-XSS-Protection "1; mode=block";
    add_header Referrer-Policy "no-referrer-when-downgrade";
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    error_page 404 /404/;

    # Static content caching
    # location /static {
    #     alias /x/podsalt/static;
    #
    #     # Set a long cache duration for images and static assets
    #     location ~* \.(jpg|jpeg|png|gif|ico|webp|svg|css|js|woff|woff2)$ {
    #         expires 365d; # Cache these files for a year
    #         add_header Cache-Control "public, no-transform";
    #
    #         # Enable ETag for cache revalidation
    #         etag on;
    #         add_header Pragma "public";
    #         add_header Vary "Accept-Encoding";
    #     }
    # }


    # location /record {
    #     default_type image/webp;
    #     alias /x/podsalt/record;
    # }

    location /app-assets {
        alias /x/podsalt/app/dist/app-assets;
    }

    location / {
        # access_log syslog:server=unix:/usr/share/nginx/socks/heimdall.dog.podsalt.sock,tag=H,nohostname heimdall;

        proxy_set_header X-Forwarded-Proto https;        
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Client-Ip $remote_addr;
        proxy_set_header Host $http_host;
        proxy_redirect off;

        proxy_pass http://podsalt_unix_sock;
    }
}
